#! /bin/bash

/bin/bash /usr/local/etc/bash_completion

_cli_bash_autocomplete() {
     local cur opts
     COMPREPLY=()
     cur="${COMP_WORDS[COMP_CWORD]}"
     opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
     if [ "$?" != 0 ]; then
         return $?
     fi
     COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
     return 0
 }

 complete -F _cli_bash_autocomplete melanite
